from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timedelta, timezone

from bson import ObjectId


def placeholder_image(title: str) -> str:
    safe_title = title.replace(" ", "+")
    return f"https://placehold.co/400x600/1f2a36/f0ead8?text={safe_title}"


MEDIA_SEED = [
    {
        "seed_key": "interstellar",
        "title": "Interstellar",
        "type": "movie",
        "genres": ["Science Fiction", "Drama", "Adventure"],
        "release_year": 2014,
        "creators": ["Christopher Nolan", "Jonathan Nolan", "Hans Zimmer"],
        "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        "description": "A future-facing space odyssey about memory, survival, and the search for a second home for humanity.",
        "ratings": {"imdb": 8.7},
        "sources": [
            {"platform": "IMDb", "url": "https://www.imdb.com/title/tt0816692/", "availability": "metadata"},
            {"platform": "Netflix", "url": "https://www.netflix.com/", "availability": "subscription"},
            {"platform": "Prime Video", "url": "https://www.primevideo.com/", "availability": "rental"},
        ],
        "tags": ["space", "time dilation", "fatherhood", "epic"],
        "related_keys": [
            {"media_key": "cosmos", "relation_type": "shared theme"},
            {"media_key": "dune_part_two", "relation_type": "science-fiction companion"},
        ],
        "thumbnail_url": placeholder_image("Interstellar"),
        "attributes": {"runtime_minutes": 169, "language": "English"},
        "added_days_ago": 2,
        "popularity_score": 96,
        "analytics": {"views": 91, "watchlisted": 40, "search_hits": 28},
    },
    {
        "seed_key": "cosmos",
        "title": "Cosmos: A Personal Voyage",
        "type": "show",
        "genres": ["Documentary", "Science", "History"],
        "release_year": 1980,
        "creators": ["Carl Sagan", "Ann Druyan", "Steven Soter"],
        "cast": ["Carl Sagan"],
        "description": "A landmark documentary series that treats scientific literacy as a shared cultural inheritance.",
        "ratings": {"imdb": 9.3},
        "sources": [
            {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=Cosmos+A+Personal+Voyage", "availability": "clips"},
            {"platform": "Internet Archive", "url": "https://archive.org/search?query=cosmos%20a%20personal%20voyage", "availability": "archival references"},
        ],
        "tags": ["space", "education", "preservation", "television history"],
        "related_keys": [{"media_key": "planet_earth_ii", "relation_type": "documentary peer"}],
        "thumbnail_url": placeholder_image("Cosmos"),
        "attributes": {"season_count": 1, "episode_count": 13},
        "added_days_ago": 12,
        "popularity_score": 88,
        "analytics": {"views": 76, "watchlisted": 23, "search_hits": 19},
    },
    {
        "seed_key": "dune_book",
        "title": "Dune",
        "type": "book",
        "genres": ["Science Fiction", "Adventure", "Politics"],
        "release_year": 1965,
        "creators": ["Frank Herbert"],
        "description": "A cornerstone novel of speculative fiction centered on ecology, empire, and destiny on the desert planet Arrakis.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/44767458-dune", "availability": "metadata"},
            {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
            {"platform": "Audible", "url": "https://www.audible.com/", "availability": "subscription"},
        ],
        "tags": ["adaptation", "desert", "worldbuilding", "classic"],
        "related_keys": [{"media_key": "dune_part_two", "relation_type": "adaptation"}],
        "thumbnail_url": placeholder_image("Dune"),
        "attributes": {"page_count": 688, "format": "Novel"},
        "added_days_ago": 8,
        "popularity_score": 90,
        "analytics": {"views": 67, "watchlisted": 31, "search_hits": 25},
    },
    {
        "seed_key": "dune_part_two",
        "title": "Dune: Part Two",
        "type": "movie",
        "genres": ["Science Fiction", "Adventure", "Drama"],
        "release_year": 2024,
        "creators": ["Denis Villeneuve", "Jon Spaihts", "Hans Zimmer"],
        "cast": ["Timothee Chalamet", "Zendaya", "Rebecca Ferguson"],
        "description": "A large-scale screen adaptation that deepens the political and spiritual stakes of Arrakis.",
        "ratings": {"imdb": 8.5},
        "sources": [
            {"platform": "IMDb", "url": "https://www.imdb.com/title/tt15239678/", "availability": "metadata"},
            {"platform": "Netflix", "url": "https://www.netflix.com/", "availability": "check region"},
            {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
        ],
        "tags": ["adaptation", "desert", "epic", "franchise"],
        "related_keys": [
            {"media_key": "dune_book", "relation_type": "based on"},
            {"media_key": "interstellar", "relation_type": "science-fiction companion"},
        ],
        "thumbnail_url": placeholder_image("Dune Part Two"),
        "attributes": {"runtime_minutes": 166, "language": "English"},
        "added_days_ago": 1,
        "popularity_score": 94,
        "analytics": {"views": 95, "watchlisted": 37, "search_hits": 30},
    },
    {
        "seed_key": "sandman",
        "title": "The Sandman, Vol. 1: Preludes & Nocturnes",
        "type": "comic",
        "genres": ["Fantasy", "Horror", "Drama"],
        "release_year": 1989,
        "creators": ["Neil Gaiman", "Sam Kieth", "Mike Dringenberg"],
        "description": "A foundational graphic storytelling work that blends mythology, dreams, and literary horror.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "DC Universe Infinite", "url": "https://www.dcuniverseinfinite.com/", "availability": "subscription"},
            {"platform": "Goodreads", "url": "https://www.goodreads.com/search?q=The+Sandman+Preludes+and+Nocturnes", "availability": "metadata"},
        ],
        "tags": ["graphic novel", "dreams", "mythology", "gothic"],
        "related_keys": [{"media_key": "spirited_away", "relation_type": "dreamlike storytelling"}],
        "thumbnail_url": placeholder_image("Sandman"),
        "attributes": {"issue_count": 8, "format": "Collected edition"},
        "added_days_ago": 14,
        "popularity_score": 82,
        "analytics": {"views": 38, "watchlisted": 18, "search_hits": 11},
    },
    {
        "seed_key": "hades",
        "title": "Hades",
        "type": "game",
        "genres": ["Action", "Roguelike", "Fantasy"],
        "release_year": 2020,
        "creators": ["Supergiant Games"],
        "description": "A fast-paced mythological action game that layers narrative progression into every escape attempt.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "Steam", "url": "https://store.steampowered.com/app/1145360/Hades/", "availability": "purchase"},
            {"platform": "Nintendo", "url": "https://www.nintendo.com/", "availability": "purchase"},
        ],
        "tags": ["mythology", "indie", "replayable", "narrative systems"],
        "related_keys": [{"media_key": "zelda_botw", "relation_type": "player crossover"}],
        "thumbnail_url": placeholder_image("Hades"),
        "attributes": {"developer": "Supergiant Games", "platforms": ["PC", "Switch", "PlayStation", "Xbox"]},
        "added_days_ago": 5,
        "popularity_score": 89,
        "analytics": {"views": 58, "watchlisted": 33, "search_hits": 15},
    },
    {
        "seed_key": "here_comes_the_sun",
        "title": "Here Comes the Sun",
        "type": "song",
        "genres": ["Rock", "Pop"],
        "release_year": 1969,
        "creators": ["George Harrison", "The Beatles"],
        "description": "A widely beloved song catalog entry that captures optimism with precise melodic craftsmanship.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "Spotify", "url": "https://open.spotify.com/search/here%20comes%20the%20sun", "availability": "streaming"},
            {"platform": "YouTube Music", "url": "https://music.youtube.com/search?q=here+comes+the+sun", "availability": "streaming"},
        ],
        "tags": ["classic rock", "optimistic", "playlist staple"],
        "related_keys": [{"media_key": "lofi_girl", "relation_type": "mood bridge"}],
        "thumbnail_url": placeholder_image("Here Comes the Sun"),
        "attributes": {"duration_seconds": 185, "album": "Abbey Road"},
        "added_days_ago": 18,
        "popularity_score": 77,
        "analytics": {"views": 44, "watchlisted": 13, "search_hits": 17},
    },
    {
        "seed_key": "planet_earth_ii",
        "title": "Planet Earth II",
        "type": "show",
        "genres": ["Documentary", "Nature", "Science"],
        "release_year": 2016,
        "creators": ["David Attenborough", "BBC Natural History Unit"],
        "cast": ["David Attenborough"],
        "description": "A sweeping natural history series that combines preservation-minded storytelling with landmark cinematography.",
        "ratings": {"imdb": 9.5},
        "sources": [
            {"platform": "BBC", "url": "https://www.bbc.co.uk/programmes/p04dv086", "availability": "official"},
            {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=planet+earth+ii", "availability": "clips"},
        ],
        "tags": ["nature", "high fidelity", "preservation", "wildlife"],
        "related_keys": [{"media_key": "cosmos", "relation_type": "documentary peer"}],
        "thumbnail_url": placeholder_image("Planet Earth II"),
        "attributes": {"season_count": 1, "episode_count": 6},
        "added_days_ago": 6,
        "popularity_score": 91,
        "analytics": {"views": 63, "watchlisted": 21, "search_hits": 20},
    },
    {
        "seed_key": "lofi_girl",
        "title": "Lofi Girl - beats to relax/study to",
        "type": "video",
        "genres": ["Music", "Ambient", "Livestream"],
        "release_year": 2020,
        "creators": ["Lofi Girl"],
        "description": "A persistent live video stream that has become an ambient study-room for internet culture.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "YouTube", "url": "https://www.youtube.com/watch?v=jfKfPfyJRdk", "availability": "free"},
            {"platform": "Spotify", "url": "https://open.spotify.com/user/lofigirl", "availability": "streaming"},
        ],
        "tags": ["study", "ambient", "youtube", "community"],
        "related_keys": [{"media_key": "here_comes_the_sun", "relation_type": "mood bridge"}],
        "thumbnail_url": placeholder_image("Lofi Girl"),
        "attributes": {"format": "Live stream", "platform": "YouTube"},
        "added_days_ago": 3,
        "popularity_score": 86,
        "analytics": {"views": 81, "watchlisted": 29, "search_hits": 26},
    },
    {
        "seed_key": "spirited_away",
        "title": "Spirited Away",
        "type": "movie",
        "genres": ["Animation", "Fantasy", "Adventure"],
        "release_year": 2001,
        "creators": ["Hayao Miyazaki", "Studio Ghibli", "Joe Hisaishi"],
        "cast": ["Rumi Hiiragi", "Miyu Irino"],
        "description": "A richly imaginative animated film where wonder, labor, memory, and identity coexist in a mythic bathhouse.",
        "ratings": {"imdb": 8.6},
        "sources": [
            {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
            {"platform": "IMDb", "url": "https://www.imdb.com/title/tt0245429/", "availability": "metadata"},
        ],
        "tags": ["animation", "coming of age", "mythic", "masterpiece"],
        "related_keys": [{"media_key": "sandman", "relation_type": "dreamlike storytelling"}],
        "thumbnail_url": placeholder_image("Spirited Away"),
        "attributes": {"runtime_minutes": 125, "language": "Japanese"},
        "added_days_ago": 4,
        "popularity_score": 92,
        "analytics": {"views": 72, "watchlisted": 34, "search_hits": 18},
    },
    {
        "seed_key": "zelda_botw",
        "title": "The Legend of Zelda: Breath of the Wild",
        "type": "game",
        "genres": ["Adventure", "Open World", "Fantasy"],
        "release_year": 2017,
        "creators": ["Nintendo EPD"],
        "description": "An expansive exploration-driven game built around curiosity, experimentation, and environmental storytelling.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "Nintendo", "url": "https://www.nintendo.com/us/store/products/the-legend-of-zelda-breath-of-the-wild-switch/", "availability": "purchase"},
            {"platform": "Metacritic", "url": "https://www.metacritic.com/game/the-legend-of-zelda-breath-of-the-wild/", "availability": "metadata"},
        ],
        "tags": ["exploration", "open world", "adventure", "landmark game"],
        "related_keys": [{"media_key": "hades", "relation_type": "player crossover"}],
        "thumbnail_url": placeholder_image("Breath of the Wild"),
        "attributes": {"developer": "Nintendo EPD", "platforms": ["Switch", "Wii U"]},
        "added_days_ago": 9,
        "popularity_score": 93,
        "analytics": {"views": 74, "watchlisted": 38, "search_hits": 22},
    },
    {
        "seed_key": "maus",
        "title": "Maus",
        "type": "comic",
        "genres": ["History", "Memoir", "Drama"],
        "release_year": 1986,
        "creators": ["Art Spiegelman"],
        "description": "A landmark graphic memoir that demonstrates the archival power of comics through testimony and form.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/15195.Maus_I", "availability": "metadata"},
            {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
        ],
        "tags": ["graphic memoir", "history", "preservation", "pulitzer"],
        "related_keys": [{"media_key": "sandman", "relation_type": "graphic storytelling canon"}],
        "thumbnail_url": placeholder_image("Maus"),
        "attributes": {"page_count": 296, "format": "Graphic memoir"},
        "added_days_ago": 20,
        "popularity_score": 79,
        "analytics": {"views": 33, "watchlisted": 14, "search_hits": 12},
    },
    {
        "seed_key": "last_of_us_game",
        "title": "The Last of Us",
        "type": "game",
        "genres": ["Action", "Drama", "Survival"],
        "release_year": 2013,
        "creators": ["Naughty Dog", "Neil Druckmann", "Gustavo Santaolalla"],
        "description": "A character-driven survival game with strong adaptation pathways across media.",
        "ratings": {"imdb": None},
        "sources": [
            {"platform": "PlayStation", "url": "https://www.playstation.com/", "availability": "purchase"},
            {"platform": "Metacritic", "url": "https://www.metacritic.com/game/the-last-of-us/", "availability": "metadata"},
        ],
        "tags": ["adaptation", "survival", "post-apocalyptic", "narrative"],
        "related_keys": [{"media_key": "last_of_us_show", "relation_type": "adaptation"}],
        "thumbnail_url": placeholder_image("The Last of Us Game"),
        "attributes": {"developer": "Naughty Dog", "platforms": ["PlayStation"]},
        "added_days_ago": 7,
        "popularity_score": 87,
        "analytics": {"views": 56, "watchlisted": 24, "search_hits": 16},
    },
    {
        "seed_key": "last_of_us_show",
        "title": "The Last of Us",
        "type": "show",
        "genres": ["Drama", "Survival", "Science Fiction"],
        "release_year": 2023,
        "creators": ["Craig Mazin", "Neil Druckmann", "HBO"],
        "cast": ["Pedro Pascal", "Bella Ramsey"],
        "description": "A television adaptation that translates interactive storytelling into prestige episodic drama.",
        "ratings": {"imdb": 8.7},
        "sources": [
            {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
            {"platform": "IMDb", "url": "https://www.imdb.com/title/tt3581920/", "availability": "metadata"},
        ],
        "tags": ["adaptation", "prestige tv", "post-apocalyptic", "relationship drama"],
        "related_keys": [{"media_key": "last_of_us_game", "relation_type": "based on"}],
        "thumbnail_url": placeholder_image("The Last of Us Show"),
        "attributes": {"season_count": 1, "episode_count": 9},
        "added_days_ago": 10,
        "popularity_score": 90,
        "analytics": {"views": 62, "watchlisted": 27, "search_hits": 18},
    },
]

MEDIA_SEED.extend(
    [
        {
            "seed_key": "arrival",
            "title": "Arrival",
            "type": "movie",
            "genres": ["Science Fiction", "Drama", "Mystery"],
            "release_year": 2016,
            "creators": ["Denis Villeneuve", "Eric Heisserer", "Johan Johannsson"],
            "cast": ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
            "description": "A cerebral first-contact film about language, grief, time, and interpretation.",
            "ratings": {"imdb": 7.9},
            "sources": [
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt2543164/", "availability": "metadata"},
                {"platform": "Prime Video", "url": "https://www.primevideo.com/", "availability": "rental"},
                {"platform": "Netflix", "url": "https://www.netflix.com/", "availability": "check region"},
            ],
            "tags": ["first contact", "language", "time", "adaptation"],
            "related_keys": [
                {"media_key": "interstellar", "relation_type": "science-fiction companion"},
                {"media_key": "left_hand_of_darkness", "relation_type": "literary resonance"},
                {"media_key": "kurzgesagt_black_hole", "relation_type": "cosmic curiosity"},
            ],
            "thumbnail_url": placeholder_image("Arrival"),
            "attributes": {"runtime_minutes": 116, "language": "English"},
            "added_days_ago": 11,
            "popularity_score": 84,
            "analytics": {"views": 59, "watchlisted": 24, "search_hits": 14},
        },
        {
            "seed_key": "matrix",
            "title": "The Matrix",
            "type": "movie",
            "genres": ["Science Fiction", "Action", "Cyberpunk"],
            "release_year": 1999,
            "creators": ["Lana Wachowski", "Lilly Wachowski", "Don Davis"],
            "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
            "description": "A landmark cyberpunk action film about systems, perception, and liberation.",
            "ratings": {"imdb": 8.7},
            "sources": [
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt0133093/", "availability": "metadata"},
                {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
                {"platform": "Prime Video", "url": "https://www.primevideo.com/", "availability": "rental"},
            ],
            "tags": ["cyberpunk", "simulation", "philosophy", "action classic"],
            "related_keys": [
                {"media_key": "neuromancer", "relation_type": "cyberpunk lineage"},
                {"media_key": "blade_runner_2049", "relation_type": "genre peer"},
                {"media_key": "portal_2", "relation_type": "systems puzzle energy"},
            ],
            "thumbnail_url": placeholder_image("The Matrix"),
            "attributes": {"runtime_minutes": 136, "language": "English"},
            "added_days_ago": 16,
            "popularity_score": 93,
            "analytics": {"views": 85, "watchlisted": 39, "search_hits": 23},
        },
        {
            "seed_key": "blade_runner_2049",
            "title": "Blade Runner 2049",
            "type": "movie",
            "genres": ["Science Fiction", "Drama", "Cyberpunk"],
            "release_year": 2017,
            "creators": ["Denis Villeneuve", "Hampton Fancher", "Roger Deakins"],
            "cast": ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
            "description": "A meditative science-fiction sequel about memory, labor, identity, and artificial life.",
            "ratings": {"imdb": 8.0},
            "sources": [
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt1856101/", "availability": "metadata"},
                {"platform": "Netflix", "url": "https://www.netflix.com/", "availability": "check region"},
                {"platform": "Prime Video", "url": "https://www.primevideo.com/", "availability": "rental"},
            ],
            "tags": ["cyberpunk", "identity", "sequel", "atmospheric"],
            "related_keys": [
                {"media_key": "matrix", "relation_type": "genre peer"},
                {"media_key": "neuromancer", "relation_type": "cyberpunk lineage"},
                {"media_key": "arrival", "relation_type": "director companion"},
            ],
            "thumbnail_url": placeholder_image("Blade Runner 2049"),
            "attributes": {"runtime_minutes": 164, "language": "English"},
            "added_days_ago": 13,
            "popularity_score": 86,
            "analytics": {"views": 65, "watchlisted": 28, "search_hits": 19},
        },
        {
            "seed_key": "princess_mononoke",
            "title": "Princess Mononoke",
            "type": "movie",
            "genres": ["Animation", "Fantasy", "Adventure"],
            "release_year": 1997,
            "creators": ["Hayao Miyazaki", "Studio Ghibli", "Joe Hisaishi"],
            "cast": ["Yoji Matsuda", "Yuriko Ishida", "Yuko Tanaka"],
            "description": "An ecological epic that frames conflict between industry, spirit, and survival without flattening any side.",
            "ratings": {"imdb": 8.3},
            "sources": [
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt0119698/", "availability": "metadata"},
                {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
                {"platform": "Apple TV", "url": "https://tv.apple.com/", "availability": "rental"},
            ],
            "tags": ["animation", "ecology", "mythic", "forest"],
            "related_keys": [
                {"media_key": "spirited_away", "relation_type": "studio companion"},
                {"media_key": "hollow_knight", "relation_type": "world mood"},
                {"media_key": "hobbit", "relation_type": "quest fantasy peer"},
            ],
            "thumbnail_url": placeholder_image("Princess Mononoke"),
            "attributes": {"runtime_minutes": 134, "language": "Japanese"},
            "added_days_ago": 15,
            "popularity_score": 88,
            "analytics": {"views": 61, "watchlisted": 27, "search_hits": 16},
        },
        {
            "seed_key": "parasite",
            "title": "Parasite",
            "type": "movie",
            "genres": ["Drama", "Thriller", "Dark Comedy"],
            "release_year": 2019,
            "creators": ["Bong Joon-ho", "Han Jin-won", "Jung Jae-il"],
            "cast": ["Song Kang-ho", "Choi Woo-shik", "Park So-dam"],
            "description": "A razor-sharp social thriller about class, architecture, labor, and aspiration.",
            "ratings": {"imdb": 8.5},
            "sources": [
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt6751668/", "availability": "metadata"},
                {"platform": "Hulu", "url": "https://www.hulu.com/", "availability": "subscription"},
                {"platform": "Prime Video", "url": "https://www.primevideo.com/", "availability": "rental"},
            ],
            "tags": ["class", "satire", "award winner", "social systems"],
            "related_keys": [
                {"media_key": "severance", "relation_type": "system critique"},
                {"media_key": "disco_elysium", "relation_type": "social systems peer"},
                {"media_key": "maus", "relation_type": "status and survival"},
            ],
            "thumbnail_url": placeholder_image("Parasite"),
            "attributes": {"runtime_minutes": 132, "language": "Korean"},
            "added_days_ago": 9,
            "popularity_score": 89,
            "analytics": {"views": 69, "watchlisted": 30, "search_hits": 21},
        },
        {
            "seed_key": "arcane",
            "title": "Arcane",
            "type": "show",
            "genres": ["Animation", "Fantasy", "Drama"],
            "release_year": 2021,
            "creators": ["Christian Linke", "Alex Yee", "Fortiche"],
            "cast": ["Hailee Steinfeld", "Ella Purnell", "Kevin Alejandro"],
            "description": "A visually ambitious animated series about class division, technology, and fractured sisterhood.",
            "ratings": {"imdb": 9.0},
            "sources": [
                {"platform": "Netflix", "url": "https://www.netflix.com/title/81435684", "availability": "subscription"},
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt11126994/", "availability": "metadata"},
            ],
            "tags": ["animation", "adaptation", "fantasy city", "stylized"],
            "related_keys": [
                {"media_key": "saga", "relation_type": "visual storytelling peer"},
                {"media_key": "hades", "relation_type": "player crossover"},
                {"media_key": "last_of_us_show", "relation_type": "adaptation prestige peer"},
            ],
            "thumbnail_url": placeholder_image("Arcane"),
            "attributes": {"season_count": 1, "episode_count": 9},
            "added_days_ago": 4,
            "popularity_score": 91,
            "analytics": {"views": 78, "watchlisted": 35, "search_hits": 25},
        },
        {
            "seed_key": "chernobyl",
            "title": "Chernobyl",
            "type": "show",
            "genres": ["Drama", "History", "Thriller"],
            "release_year": 2019,
            "creators": ["Craig Mazin", "HBO", "Johan Renck"],
            "cast": ["Jared Harris", "Stellan Skarsgard", "Emily Watson"],
            "description": "A tense historical miniseries about catastrophe, evidence, and institutional denial.",
            "ratings": {"imdb": 9.3},
            "sources": [
                {"platform": "Max", "url": "https://www.max.com/", "availability": "subscription"},
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt7366338/", "availability": "metadata"},
            ],
            "tags": ["history", "disaster", "institutional failure", "prestige tv"],
            "related_keys": [
                {"media_key": "last_of_us_show", "relation_type": "shared creator"},
                {"media_key": "planet_earth_ii", "relation_type": "documented reality contrast"},
                {"media_key": "maus", "relation_type": "historic testimony"},
            ],
            "thumbnail_url": placeholder_image("Chernobyl"),
            "attributes": {"season_count": 1, "episode_count": 5},
            "added_days_ago": 21,
            "popularity_score": 83,
            "analytics": {"views": 54, "watchlisted": 22, "search_hits": 13},
        },
        {
            "seed_key": "severance",
            "title": "Severance",
            "type": "show",
            "genres": ["Science Fiction", "Thriller", "Drama"],
            "release_year": 2022,
            "creators": ["Dan Erickson", "Ben Stiller", "Apple TV+"],
            "cast": ["Adam Scott", "Britt Lower", "Patricia Arquette"],
            "description": "A workplace science-fiction series about compartmentalized identity, labor, and corporate ritual.",
            "ratings": {"imdb": 8.7},
            "sources": [
                {"platform": "Apple TV", "url": "https://tv.apple.com/", "availability": "subscription"},
                {"platform": "IMDb", "url": "https://www.imdb.com/title/tt11280740/", "availability": "metadata"},
            ],
            "tags": ["workplace", "identity", "science fiction", "office dystopia"],
            "related_keys": [
                {"media_key": "matrix", "relation_type": "systems paranoia"},
                {"media_key": "parasite", "relation_type": "class anxiety"},
                {"media_key": "disco_elysium", "relation_type": "fractured identity"},
            ],
            "thumbnail_url": placeholder_image("Severance"),
            "attributes": {"season_count": 1, "episode_count": 9},
            "added_days_ago": 6,
            "popularity_score": 85,
            "analytics": {"views": 57, "watchlisted": 26, "search_hits": 17},
        },
        {
            "seed_key": "blue_planet_ii",
            "title": "Blue Planet II",
            "type": "show",
            "genres": ["Documentary", "Nature", "Science"],
            "release_year": 2017,
            "creators": ["David Attenborough", "BBC Natural History Unit"],
            "cast": ["David Attenborough"],
            "description": "A high-fidelity ocean documentary series about marine life, fragility, and stewardship.",
            "ratings": {"imdb": 9.3},
            "sources": [
                {"platform": "BBC", "url": "https://www.bbc.co.uk/programmes/p04tjbtx", "availability": "official"},
                {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=blue+planet+ii", "availability": "clips"},
            ],
            "tags": ["documentary", "ocean", "preservation", "wildlife"],
            "related_keys": [
                {"media_key": "planet_earth_ii", "relation_type": "documentary companion"},
                {"media_key": "cosmos", "relation_type": "science documentation peer"},
            ],
            "thumbnail_url": placeholder_image("Blue Planet II"),
            "attributes": {"season_count": 1, "episode_count": 7},
            "added_days_ago": 17,
            "popularity_score": 80,
            "analytics": {"views": 47, "watchlisted": 17, "search_hits": 12},
        },
        {
            "seed_key": "left_hand_of_darkness",
            "title": "The Left Hand of Darkness",
            "type": "book",
            "genres": ["Science Fiction", "Politics", "Philosophy"],
            "release_year": 1969,
            "creators": ["Ursula K. Le Guin"],
            "description": "A foundational science-fiction novel using planetary anthropology to examine gender, diplomacy, and estrangement.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/18423.The_Left_Hand_of_Darkness", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
                {"platform": "Audible", "url": "https://www.audible.com/", "availability": "subscription"},
            ],
            "tags": ["anthropology", "first contact", "classic", "political sci-fi"],
            "related_keys": [
                {"media_key": "arrival", "relation_type": "literary resonance"},
                {"media_key": "dune_book", "relation_type": "science-fiction canon"},
                {"media_key": "foundation", "relation_type": "genre shelf"},
            ],
            "thumbnail_url": placeholder_image("Left Hand of Darkness"),
            "attributes": {"page_count": 304, "format": "Novel"},
            "added_days_ago": 18,
            "popularity_score": 78,
            "analytics": {"views": 35, "watchlisted": 16, "search_hits": 11},
        },
        {
            "seed_key": "neuromancer",
            "title": "Neuromancer",
            "type": "book",
            "genres": ["Science Fiction", "Cyberpunk", "Thriller"],
            "release_year": 1984,
            "creators": ["William Gibson"],
            "description": "A defining cyberpunk novel about networks, corporations, console cowboys, and virtual space.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/22328.Neuromancer", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
                {"platform": "Audible", "url": "https://www.audible.com/", "availability": "subscription"},
            ],
            "tags": ["cyberpunk", "hacker", "classic", "virtual reality"],
            "related_keys": [
                {"media_key": "matrix", "relation_type": "cyberpunk lineage"},
                {"media_key": "blade_runner_2049", "relation_type": "genre peer"},
                {"media_key": "portal_2", "relation_type": "systems thinking"},
            ],
            "thumbnail_url": placeholder_image("Neuromancer"),
            "attributes": {"page_count": 271, "format": "Novel"},
            "added_days_ago": 19,
            "popularity_score": 81,
            "analytics": {"views": 39, "watchlisted": 18, "search_hits": 13},
        },
    ]
)

MEDIA_SEED.extend(
    [
        {
            "seed_key": "kindred",
            "title": "Kindred",
            "type": "book",
            "genres": ["Science Fiction", "History", "Drama"],
            "release_year": 1979,
            "creators": ["Octavia E. Butler"],
            "description": "A time-travel novel that fuses speculative form with lived history, lineage, and survival.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/60931.Kindred", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
                {"platform": "Audible", "url": "https://www.audible.com/", "availability": "subscription"},
            ],
            "tags": ["time travel", "history", "lineage", "speculative classic"],
            "related_keys": [
                {"media_key": "maus", "relation_type": "historic testimony peer"},
                {"media_key": "persepolis", "relation_type": "memory and survival"},
                {"media_key": "disco_elysium", "relation_type": "social history"},
            ],
            "thumbnail_url": placeholder_image("Kindred"),
            "attributes": {"page_count": 288, "format": "Novel"},
            "added_days_ago": 10,
            "popularity_score": 77,
            "analytics": {"views": 31, "watchlisted": 15, "search_hits": 10},
        },
        {
            "seed_key": "hobbit",
            "title": "The Hobbit",
            "type": "book",
            "genres": ["Fantasy", "Adventure", "Classic"],
            "release_year": 1937,
            "creators": ["J.R.R. Tolkien"],
            "description": "A quest novel whose map-like sense of travel shaped modern fantasy across media.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/5907.The_Hobbit", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
                {"platform": "Audible", "url": "https://www.audible.com/", "availability": "subscription"},
            ],
            "tags": ["quest", "fantasy", "classic", "worldbuilding"],
            "related_keys": [
                {"media_key": "zelda_botw", "relation_type": "exploration lineage"},
                {"media_key": "princess_mononoke", "relation_type": "quest fantasy peer"},
                {"media_key": "hollow_knight", "relation_type": "journey into the unknown"},
            ],
            "thumbnail_url": placeholder_image("The Hobbit"),
            "attributes": {"page_count": 310, "format": "Novel"},
            "added_days_ago": 22,
            "popularity_score": 82,
            "analytics": {"views": 43, "watchlisted": 20, "search_hits": 15},
        },
        {
            "seed_key": "foundation",
            "title": "Foundation",
            "type": "book",
            "genres": ["Science Fiction", "Politics", "Classic"],
            "release_year": 1951,
            "creators": ["Isaac Asimov"],
            "description": "A classic future-history novel cycle about prediction, empire, and the long arc of institutions.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/29579.Foundation", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
                {"platform": "Apple Books", "url": "https://books.apple.com/", "availability": "purchase"},
            ],
            "tags": ["empire", "classic", "future history", "grand scale"],
            "related_keys": [
                {"media_key": "dune_book", "relation_type": "science-fiction canon"},
                {"media_key": "cosmos", "relation_type": "history of ideas"},
                {"media_key": "left_hand_of_darkness", "relation_type": "genre shelf"},
            ],
            "thumbnail_url": placeholder_image("Foundation"),
            "attributes": {"page_count": 255, "format": "Novel"},
            "added_days_ago": 23,
            "popularity_score": 74,
            "analytics": {"views": 29, "watchlisted": 12, "search_hits": 9},
        },
        {
            "seed_key": "watchmen",
            "title": "Watchmen",
            "type": "comic",
            "genres": ["Drama", "Science Fiction", "Mystery"],
            "release_year": 1987,
            "creators": ["Alan Moore", "Dave Gibbons", "John Higgins"],
            "description": "A canonical graphic work about power, surveillance, media, and fractured heroism.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/472331.Watchmen", "availability": "metadata"},
                {"platform": "DC Universe Infinite", "url": "https://www.dcuniverseinfinite.com/", "availability": "subscription"},
            ],
            "tags": ["graphic novel", "superhero deconstruction", "classic", "politics"],
            "related_keys": [
                {"media_key": "matrix", "relation_type": "systems paranoia"},
                {"media_key": "maus", "relation_type": "graphic canon"},
                {"media_key": "severance", "relation_type": "control and surveillance"},
            ],
            "thumbnail_url": placeholder_image("Watchmen"),
            "attributes": {"issue_count": 12, "format": "Collected edition"},
            "added_days_ago": 24,
            "popularity_score": 79,
            "analytics": {"views": 34, "watchlisted": 14, "search_hits": 10},
        },
        {
            "seed_key": "saga",
            "title": "Saga, Vol. 1",
            "type": "comic",
            "genres": ["Fantasy", "Science Fiction", "Drama"],
            "release_year": 2012,
            "creators": ["Brian K. Vaughan", "Fiona Staples"],
            "description": "A cross-genre graphic saga blending family drama, space opera, and visual invention.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/15704307-saga-vol-1", "availability": "metadata"},
                {"platform": "Image Comics", "url": "https://imagecomics.com/comics/series/saga", "availability": "official"},
            ],
            "tags": ["graphic novel", "space opera", "family", "visual storytelling"],
            "related_keys": [
                {"media_key": "arcane", "relation_type": "visual storytelling peer"},
                {"media_key": "sandman", "relation_type": "graphic storytelling canon"},
                {"media_key": "dune_book", "relation_type": "space-opera shelf"},
            ],
            "thumbnail_url": placeholder_image("Saga"),
            "attributes": {"issue_count": 6, "format": "Collected edition"},
            "added_days_ago": 5,
            "popularity_score": 83,
            "analytics": {"views": 36, "watchlisted": 17, "search_hits": 12},
        },
        {
            "seed_key": "persepolis",
            "title": "Persepolis",
            "type": "comic",
            "genres": ["Memoir", "History", "Drama"],
            "release_year": 2000,
            "creators": ["Marjane Satrapi"],
            "description": "A graphic memoir of political upheaval, adolescence, migration, and voice.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Goodreads", "url": "https://www.goodreads.com/book/show/9516.Persepolis", "availability": "metadata"},
                {"platform": "Google Books", "url": "https://books.google.com/", "availability": "preview"},
            ],
            "tags": ["graphic memoir", "history", "identity", "memoir"],
            "related_keys": [
                {"media_key": "maus", "relation_type": "graphic memoir peer"},
                {"media_key": "kindred", "relation_type": "memory and survival"},
                {"media_key": "chernobyl", "relation_type": "history through lived experience"},
            ],
            "thumbnail_url": placeholder_image("Persepolis"),
            "attributes": {"page_count": 341, "format": "Graphic memoir"},
            "added_days_ago": 12,
            "popularity_score": 76,
            "analytics": {"views": 28, "watchlisted": 11, "search_hits": 9},
        },
        {
            "seed_key": "outer_wilds",
            "title": "Outer Wilds",
            "type": "game",
            "genres": ["Adventure", "Exploration", "Science Fiction"],
            "release_year": 2019,
            "creators": ["Mobius Digital", "Annapurna Interactive"],
            "description": "A time-loop exploration game about curiosity, archaeology, and cosmic scale.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Steam", "url": "https://store.steampowered.com/app/753640/Outer_Wilds/", "availability": "purchase"},
                {"platform": "PlayStation", "url": "https://www.playstation.com/", "availability": "purchase"},
            ],
            "tags": ["exploration", "time loop", "space", "indie"],
            "related_keys": [
                {"media_key": "interstellar", "relation_type": "cosmic curiosity"},
                {"media_key": "noclip_outer_wilds", "relation_type": "development documentary"},
                {"media_key": "cosmos", "relation_type": "science wonder"},
            ],
            "thumbnail_url": placeholder_image("Outer Wilds"),
            "attributes": {"developer": "Mobius Digital", "platforms": ["PC", "Switch", "PlayStation", "Xbox"]},
            "added_days_ago": 3,
            "popularity_score": 92,
            "analytics": {"views": 77, "watchlisted": 41, "search_hits": 26},
        },
        {
            "seed_key": "disco_elysium",
            "title": "Disco Elysium",
            "type": "game",
            "genres": ["Role-Playing", "Mystery", "Drama"],
            "release_year": 2019,
            "creators": ["ZA/UM"],
            "description": "A text-rich role-playing game about ideology, memory, labor, and urban history.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Steam", "url": "https://store.steampowered.com/app/632470/Disco_Elysium__The_Final_Cut/", "availability": "purchase"},
                {"platform": "GOG", "url": "https://www.gog.com/", "availability": "purchase"},
            ],
            "tags": ["rpg", "investigation", "politics", "writing"],
            "related_keys": [
                {"media_key": "parasite", "relation_type": "social systems peer"},
                {"media_key": "kindred", "relation_type": "social history"},
                {"media_key": "severance", "relation_type": "fractured identity"},
            ],
            "thumbnail_url": placeholder_image("Disco Elysium"),
            "attributes": {"developer": "ZA/UM", "platforms": ["PC", "PlayStation", "Xbox", "Switch"]},
            "added_days_ago": 8,
            "popularity_score": 87,
            "analytics": {"views": 52, "watchlisted": 29, "search_hits": 16},
        },
        {
            "seed_key": "portal_2",
            "title": "Portal 2",
            "type": "game",
            "genres": ["Puzzle", "Science Fiction", "Comedy"],
            "release_year": 2011,
            "creators": ["Valve"],
            "description": "A puzzle game that turns systems thinking, architecture, and comic timing into elegant play.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Steam", "url": "https://store.steampowered.com/app/620/Portal_2/", "availability": "purchase"},
                {"platform": "Nintendo", "url": "https://www.nintendo.com/", "availability": "purchase"},
            ],
            "tags": ["puzzle", "systems", "comedy", "co-op"],
            "related_keys": [
                {"media_key": "matrix", "relation_type": "systems puzzle energy"},
                {"media_key": "neuromancer", "relation_type": "systems thinking"},
                {"media_key": "outer_wilds", "relation_type": "design curiosity"},
            ],
            "thumbnail_url": placeholder_image("Portal 2"),
            "attributes": {"developer": "Valve", "platforms": ["PC", "PlayStation", "Xbox", "Switch"]},
            "added_days_ago": 14,
            "popularity_score": 84,
            "analytics": {"views": 49, "watchlisted": 25, "search_hits": 14},
        },
        {
            "seed_key": "hollow_knight",
            "title": "Hollow Knight",
            "type": "game",
            "genres": ["Action", "Adventure", "Fantasy"],
            "release_year": 2017,
            "creators": ["Team Cherry"],
            "description": "A moody exploratory action game built around ruins, lore fragments, and spatial discovery.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Steam", "url": "https://store.steampowered.com/app/367520/Hollow_Knight/", "availability": "purchase"},
                {"platform": "Nintendo", "url": "https://www.nintendo.com/", "availability": "purchase"},
            ],
            "tags": ["metroidvania", "atmospheric", "indie", "exploration"],
            "related_keys": [
                {"media_key": "princess_mononoke", "relation_type": "world mood"},
                {"media_key": "hades", "relation_type": "indie action peer"},
                {"media_key": "hobbit", "relation_type": "journey into the unknown"},
            ],
            "thumbnail_url": placeholder_image("Hollow Knight"),
            "attributes": {"developer": "Team Cherry", "platforms": ["PC", "Switch", "PlayStation", "Xbox"]},
            "added_days_ago": 7,
            "popularity_score": 86,
            "analytics": {"views": 53, "watchlisted": 27, "search_hits": 15},
        },
        {
            "seed_key": "bohemian_rhapsody",
            "title": "Bohemian Rhapsody",
            "type": "song",
            "genres": ["Rock", "Progressive Rock"],
            "release_year": 1975,
            "creators": ["Freddie Mercury", "Queen"],
            "description": "A maximalist rock suite that still functions as a communal singalong artifact.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "Spotify", "url": "https://open.spotify.com/search/bohemian%20rhapsody", "availability": "streaming"},
                {"platform": "YouTube Music", "url": "https://music.youtube.com/search?q=bohemian+rhapsody", "availability": "streaming"},
            ],
            "tags": ["classic rock", "anthem", "operatic", "canon"],
            "related_keys": [
                {"media_key": "here_comes_the_sun", "relation_type": "classic song shelf"},
                {"media_key": "tiny_desk_aurora", "relation_type": "live performance pathway"},
                {"media_key": "lofi_girl", "relation_type": "playlist contrast"},
            ],
            "thumbnail_url": placeholder_image("Bohemian Rhapsody"),
            "attributes": {"duration_seconds": 354, "album": "A Night at the Opera"},
            "added_days_ago": 25,
            "popularity_score": 75,
            "analytics": {"views": 37, "watchlisted": 12, "search_hits": 11},
        },
        {
            "seed_key": "kurzgesagt_black_hole",
            "title": "Kurzgesagt - Black Hole Stars",
            "type": "video",
            "genres": ["Science", "Education", "Animation"],
            "release_year": 2021,
            "creators": ["Kurzgesagt"],
            "description": "An animated science explainer using visual clarity and compression to make extreme physics approachable.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=kurzgesagt+black+hole+stars", "availability": "free"},
                {"platform": "Kurzgesagt", "url": "https://kurzgesagt.org/", "availability": "official"},
            ],
            "tags": ["science explainer", "space", "education", "animation"],
            "related_keys": [
                {"media_key": "cosmos", "relation_type": "science communication peer"},
                {"media_key": "interstellar", "relation_type": "cosmic curiosity"},
                {"media_key": "arrival", "relation_type": "science wonder"},
            ],
            "thumbnail_url": placeholder_image("Kurzgesagt Black Hole"),
            "attributes": {"format": "Essay video", "platform": "YouTube"},
            "added_days_ago": 2,
            "popularity_score": 82,
            "analytics": {"views": 63, "watchlisted": 20, "search_hits": 22},
        },
        {
            "seed_key": "noclip_outer_wilds",
            "title": "Noclip Documentary: The Making of Outer Wilds",
            "type": "video",
            "genres": ["Documentary", "Games", "Interview"],
            "release_year": 2020,
            "creators": ["Noclip"],
            "description": "A documentary video about the making of a systems-driven exploration game and its design choices.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=noclip+outer+wilds", "availability": "free"},
                {"platform": "Noclip", "url": "https://www.noclip.video/", "availability": "official"},
            ],
            "tags": ["game documentary", "design", "behind the scenes", "youtube"],
            "related_keys": [
                {"media_key": "outer_wilds", "relation_type": "development documentary"},
                {"media_key": "hades", "relation_type": "design process peer"},
                {"media_key": "disco_elysium", "relation_type": "games criticism shelf"},
            ],
            "thumbnail_url": placeholder_image("Noclip Outer Wilds"),
            "attributes": {"format": "Documentary video", "platform": "YouTube"},
            "added_days_ago": 1,
            "popularity_score": 79,
            "analytics": {"views": 58, "watchlisted": 18, "search_hits": 20},
        },
        {
            "seed_key": "tiny_desk_aurora",
            "title": "Tiny Desk Concert: AURORA",
            "type": "video",
            "genres": ["Music", "Performance", "Live Session"],
            "release_year": 2023,
            "creators": ["NPR Music", "AURORA"],
            "description": "A stripped-back live session highlighting arrangement, voice, and room-scale intimacy.",
            "ratings": {"imdb": None},
            "sources": [
                {"platform": "YouTube", "url": "https://www.youtube.com/results?search_query=tiny+desk+aurora", "availability": "free"},
                {"platform": "NPR Music", "url": "https://www.npr.org/series/tiny-desk-concerts/", "availability": "official"},
            ],
            "tags": ["live music", "performance", "session", "youtube"],
            "related_keys": [
                {"media_key": "bohemian_rhapsody", "relation_type": "performance pathway"},
                {"media_key": "lofi_girl", "relation_type": "listening context contrast"},
                {"media_key": "here_comes_the_sun", "relation_type": "song shelf"},
            ],
            "thumbnail_url": placeholder_image("Tiny Desk Aurora"),
            "attributes": {"format": "Live performance", "platform": "YouTube"},
            "added_days_ago": 6,
            "popularity_score": 73,
            "analytics": {"views": 34, "watchlisted": 9, "search_hits": 8},
        },
    ]
)

USER_SEED = [
    {
        "seed_key": "archive_curator",
        "username": "archive_curator",
        "preferences": ["Science Fiction", "Documentary", "space", "adaptation", "worldbuilding"],
        "watchlist_keys": ["dune_part_two", "planet_earth_ii", "last_of_us_show"],
        "history_keys": ["cosmos", "interstellar", "dune_book"],
    },
    {
        "seed_key": "mythic_player",
        "username": "mythic_player",
        "preferences": ["Fantasy", "mythology", "animation", "graphic novel", "adventure"],
        "watchlist_keys": ["sandman", "spirited_away"],
        "history_keys": ["hades", "zelda_botw"],
    },
    {
        "seed_key": "video_nomad",
        "username": "video_nomad",
        "preferences": ["Music", "study", "youtube", "ambient", "relaxation"],
        "watchlist_keys": ["here_comes_the_sun"],
        "history_keys": ["lofi_girl", "planet_earth_ii"],
    },
]

USER_SEED.extend(
    [
        {
            "seed_key": "cyber_cartographer",
            "username": "cyber_cartographer",
            "preferences": ["Cyberpunk", "Science Fiction", "systems", "identity", "politics"],
            "watchlist_keys": ["matrix", "blade_runner_2049", "neuromancer"],
            "history_keys": ["arrival", "severance", "portal_2"],
        },
        {
            "seed_key": "quiet_stacks",
            "username": "quiet_stacks",
            "preferences": ["History", "Memoir", "preservation", "graphic memoir", "documentary"],
            "watchlist_keys": ["persepolis", "chernobyl", "blue_planet_ii"],
            "history_keys": ["maus", "planet_earth_ii", "kindred"],
        },
        {
            "seed_key": "mycelial_reader",
            "username": "mycelial_reader",
            "preferences": ["Fantasy", "ecology", "worldbuilding", "animation", "exploration"],
            "watchlist_keys": ["princess_mononoke", "hobbit", "arcane"],
            "history_keys": ["spirited_away", "zelda_botw", "hollow_knight"],
        },
        {
            "seed_key": "signal_booster",
            "username": "signal_booster",
            "preferences": ["Music", "youtube", "live music", "ambient", "community"],
            "watchlist_keys": ["tiny_desk_aurora", "bohemian_rhapsody"],
            "history_keys": ["lofi_girl", "kurzgesagt_black_hole", "here_comes_the_sun"],
        },
    ]
)

REVIEW_SEED = [
    {
        "user_key": "archive_curator",
        "media_key": "interstellar",
        "rating": 9.4,
        "comment": "A deeply archival kind of science fiction, where memory itself becomes part of the mission architecture.",
    },
    {
        "user_key": "archive_curator",
        "media_key": "dune_book",
        "rating": 9.1,
        "comment": "Still one of the strongest examples of worldbuilding that scales across formats without losing complexity.",
    },
    {
        "user_key": "mythic_player",
        "media_key": "hades",
        "rating": 9.6,
        "comment": "The repetition is the point; every run uncovers another layer of character, style, and systems design.",
    },
    {
        "user_key": "mythic_player",
        "media_key": "spirited_away",
        "rating": 9.3,
        "comment": "Dense with image-making and emotion, but still welcoming enough to feel timeless on every revisit.",
    },
    {
        "user_key": "video_nomad",
        "media_key": "lofi_girl",
        "rating": 8.8,
        "comment": "More than a stream now; it feels like a preserved ambient room for the internet.",
    },
    {
        "user_key": "video_nomad",
        "media_key": "planet_earth_ii",
        "rating": 9.0,
        "comment": "The production quality makes it easy to forget how much patient natural history documentation sits underneath it.",
    },
]

REVIEW_SEED.extend(
    [
        {
            "user_key": "archive_curator",
            "media_key": "foundation",
            "rating": 8.6,
            "comment": "A key archival branch of future-history storytelling even when the character texture stays deliberately schematic.",
        },
        {
            "user_key": "mythic_player",
            "media_key": "hollow_knight",
            "rating": 9.2,
            "comment": "The map slowly becomes a memory palace, which is exactly why the world stays with you.",
        },
        {
            "user_key": "video_nomad",
            "media_key": "tiny_desk_aurora",
            "rating": 8.7,
            "comment": "A compact reminder that live performance videos can function as archive entries in their own right.",
        },
        {
            "user_key": "cyber_cartographer",
            "media_key": "matrix",
            "rating": 9.5,
            "comment": "Still one of the clearest bridges between philosophy-pop discourse and blockbuster form.",
        },
        {
            "user_key": "cyber_cartographer",
            "media_key": "neuromancer",
            "rating": 8.9,
            "comment": "Dense, slippery, and foundational; a metadata hub for half the cyberpunk shelf.",
        },
        {
            "user_key": "cyber_cartographer",
            "media_key": "severance",
            "rating": 9.1,
            "comment": "The office aesthetics land because the show treats workflow as ritual rather than background detail.",
        },
        {
            "user_key": "quiet_stacks",
            "media_key": "persepolis",
            "rating": 9.1,
            "comment": "The visual economy sharpens the testimony instead of shrinking it.",
        },
        {
            "user_key": "quiet_stacks",
            "media_key": "chernobyl",
            "rating": 8.8,
            "comment": "A dramatized archive of procedural failure that still points you back toward documents and evidence.",
        },
        {
            "user_key": "quiet_stacks",
            "media_key": "blue_planet_ii",
            "rating": 8.9,
            "comment": "The ocean footage works, but the preservation framing is what gives it lasting weight.",
        },
        {
            "user_key": "mycelial_reader",
            "media_key": "princess_mononoke",
            "rating": 9.5,
            "comment": "Its refusal to simplify ecological conflict is exactly what makes it feel alive decades later.",
        },
        {
            "user_key": "mycelial_reader",
            "media_key": "hobbit",
            "rating": 8.7,
            "comment": "You can still feel the template for adventure design radiating out from it.",
        },
        {
            "user_key": "mycelial_reader",
            "media_key": "arcane",
            "rating": 9.0,
            "comment": "The animation is dazzling, but the real draw is how clearly every environment carries social meaning.",
        },
        {
            "user_key": "signal_booster",
            "media_key": "bohemian_rhapsody",
            "rating": 8.6,
            "comment": "A permanent communal object: half recording, half ritual.",
        },
        {
            "user_key": "signal_booster",
            "media_key": "kurzgesagt_black_hole",
            "rating": 8.5,
            "comment": "Short-form education that still leaves a useful trail of ideas to follow outward.",
        },
        {
            "user_key": "signal_booster",
            "media_key": "noclip_outer_wilds",
            "rating": 8.8,
            "comment": "A strong example of criticism, documentary, and creator interview merging into one archive entry.",
        },
    ]
)


def build_seed_payload() -> tuple[list[dict], list[dict], list[dict]]:
    now = datetime.now(timezone.utc)

    media_ids = {item["seed_key"]: ObjectId() for item in MEDIA_SEED}
    user_ids = {item["seed_key"]: ObjectId() for item in USER_SEED}

    media_documents = []
    for item in MEDIA_SEED:
        document = deepcopy(item)
        document["_id"] = media_ids[item["seed_key"]]
        document["related"] = [
            {
                "media_id": media_ids[relation["media_key"]],
                "relation_type": relation["relation_type"],
            }
            for relation in document.pop("related_keys", [])
        ]
        document["added_at"] = now - timedelta(days=document.pop("added_days_ago", 0))
        document.pop("seed_key")
        media_documents.append(document)

    user_documents = []
    for item in USER_SEED:
        document = deepcopy(item)
        document["_id"] = user_ids[item["seed_key"]]
        document["watchlist"] = [media_ids[key] for key in document.pop("watchlist_keys", [])]
        document["history"] = [media_ids[key] for key in document.pop("history_keys", [])]
        document["created_at"] = now - timedelta(days=30)
        document.pop("seed_key")
        user_documents.append(document)

    review_documents = []
    for index, item in enumerate(REVIEW_SEED, start=1):
        review_documents.append(
            {
                "_id": ObjectId(),
                "user_id": user_ids[item["user_key"]],
                "media_id": media_ids[item["media_key"]],
                "rating": item["rating"],
                "comment": item["comment"],
                "created_at": now - timedelta(hours=index * 7),
            }
        )

    return media_documents, user_documents, review_documents
